---
- name: create source volume
  hosts: "localhost"
  become: no
  gather_facts: no
  vars:
    cluster: "{{ source.cluster }}"
    aggregate: "{{ source.aggregate }}"
    svm: "{{ source.svm }}"
    volname: "{{ source.volname }}"
    junctionpath: "{{ '/'+volname }}"
    junctionpathqtree: "{{ junctionpath + '/' + volname }}"
    secstyle: "{{ source.secstyle | default(volume_defaults.secstyle) | default(omit) }}"
    volsize: "{{ source.volsize|int | default(50) }}"
    clusterauth:  &login
      hostname: "{{ cluster }}"
      username: "{{ ontap_username }}"
      password: "{{ ontap_password}}"
      https: true
      validate_certs: false
  vars_files:
  #- volume_variables.yaml
  - ./globals.yml

  collections:
  - netapp.ontap
  tasks:
    - name: Create prod volume
      na_ontap_volume:
        state: present
        aggregate_name: "{{ aggregate }}"
        name: "{{ volname }}"
        vserver: "{{ svm }}"
        size: "{{ volsize|int }}"
        size_unit: mb
        junction_path: "{{ junctionpath }}"
        wait_for_completion: yes
        <<: *login

    - name: Create qtree
      na_ontap_qtree:
        state: present
        flexvol_name: "{{ volname }}"
        name: "{{ volname }}"
        vserver: "{{ svm }}"
        <<: *login

    - name: Create cifs
      na_ontap_cifs:
        state: present
        share_name: "{{ volname }}"
        vserver: "{{ svm }}"
        path: "{{ junctionpathqtree }}"
        <<: *login
